[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "gnumake", "pkg-config"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm rebuild better-sqlite3 --build-from-source"]

[start]
cmd = "npm start"
